_BASE_: Base-naic.yml

MODEL:
  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 34x
    FEAT_DIM: 512
    WITH_IBN: True
    PRETRAIN: True

OUTPUT_DIR: projects/NAIC20/log_veri_last/r34_ibn-128x256